### ISSUE TITLE
TwitterEmoticon dataset?

### ISSUE THREAD

**Issue by AADeLucia** [Stefanos-stk/Covid19Twitter#12]
I read the "Multilingual Emoticon Prediction of Tweets about COVID-19" paper and I am interested in the TwitterEmoticon dataset. I see this repo has `bertmoticon_covid_dataset_part-*.gz` files, but I don't see other dataset files. Is the TwitterEmoticon dataset available? Thanks!

**Comment by Stefanos-stk** [comment]
Here is the link/instructions to download the dataset: https://github.com/Stefanos-stk/Bertmoticon/blob/master/README.md#twittercovid-dataset

**Comment by Stefanos-stk** [comment]
Here is the link for the TwitterEmoticon Dataset: https://github.com/Stefanos-stk/Bertmoticon#twitteremoticon-dataset

**Comment by AADeLucia** [comment]
Great, thanks!
