### ISSUE TITLE
sql database 

### ISSUE THREAD

**Issue by Stefanos-stk** [Stefanos-stk/Covid19Twitter#3]
I am having a small issue with the example.py file. I downloaded all the libraries that it required. The original example.py file has commented on the SQL code that finds the tweets. When I removed that I got this error: 
```
  File "example.py", line 10
    date_trunc('day',created_at) as day,
             ^
SyntaxError: invalid syntax
```
and when I inserted the comments back I got this error:
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for schema twitter
LINE 5: FROM twitter.tweet_tags
```
This is another error when I try to run the commands on their own in the psql bot:
```
ERROR:  permission denied for schema twitter
```

**Comment by mikeizbicki** [comment]
Sorry, I had your permissions misconfigured.  The commands should work now.

**Comment by Stefanos-stk** [comment]
I haven't been able to work the commands yet I am getting this Fatal error:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: the database system is in recovery mode
```

**Comment by Stefanos-stk** [comment]
I tried running the nohup python3 file.py command 
I got this output and nothing seems to be happening (nothing gets added)
```
ssaa2018@lambda-server:~/sentiment_discovery_nvidia/sentiment-discovery$ nohup python3 sqlSent.py 
nohup: ignoring input and appending output to 'nohup.out'
```

**Comment by Stefanos-stk** [comment]
I am not sure if I can get the Bert up and running soon, so if you could send me the solution that would be great. I tried a lot of stuff but I kept bumping into rabbit holes of debugging. 

Also, I am running this command:
```
    date_trunc('day',created_at) as day,avg(anger),stddev(anger) 
    FROM twitter.tweet_sentiment inner join twitter.tweets on tweet_sentiment.id_tweets=tweets.id_tweets 
    group by day order by day desc;
```
to get the sentiments for each day, however this is taking a while now (20 minutes). I am going to run more tweets to get evaluated and sent to the database so we have more data. Is this going to cause the other process to slow down? I am assuming the rated tweets are on a different site than the existing non-rated ones (the raw tweets)

**Comment by mikeizbicki** [comment]
I've added files `names_transformers.py` and `names_embeddings.py` to the
project folder, which are the solutions to parts 2 and 3: https://github.com/mik
eizbicki/cmc-csci181/blob/master/project/names_transformers.py

You can run
```
$ diff names.py names_transformers.py
```
to see what the exact changes I made for the solution are.
